services:
  node1:
    build: .
    environment:
      - NODE_ID=node1
      - LOG_FILE=/logs/node1.log
      - PORT=5000
    ports:
      - "5001:5000"
    volumes:
      - ./logs:/logs

  node2:
    build: .
    environment:
      - NODE_ID=node2
      - LOG_FILE=/logs/node2.log
      - PORT=5000
    ports:
      - "5002:5000"
    volumes:
      - ./logs:/logs

  node3:
    build: .
    environment:
      - NODE_ID=node3
      - LOG_FILE=/logs/node3.log
      - PORT=5000
    ports:
      - "5003:5000"
    volumes:
      - ./logs:/logs

  node4:
    build: .
    environment:
      - NODE_ID=node4
      - LOG_FILE=/logs/node4.log
      - PORT=5000
    ports:
      - "5004:5000"
    volumes:
      - ./logs:/logs
